version: "3.8"

services:
    ruby:
        build:
            context: ./docker/ruby
            dockerfile: Dockerfile
        command: tail -F anything
        volumes:
            - .:/usr/src/app
